Repository scania/corporate-ui-react, pull requests merged in 2019-12, with the labels that each got.

#13 Update function to import custom element
  src/components/Content/Content.js
  src/components/Footer/Footer.js
  src/components/Header/Header.js
  src/index.js
Labels: enhancement

#16 Update corporate-ui dependency
  .dependabot/config.yml
  README.md
  package.json
  src/index.js
Labels: Improvement

#17 FIx for ie
  .gitignore
  package-lock.json
  package.json
  src/components/Content/Content.js
  src/components/Header/Header.js
  src/index.js
  src/scenes/Home/Home.js
Labels: Feature
